### ISSUE TITLE
Fix _printString to work with _printChar

### ISSUE THREAD

**Issue by The-Dankest** [DankZ-CpS230Team/teamProject#12]
Changes:
- Use _printChar to print each character
- Store the address of the first character in AX
- Pass the character at that address to _printChar

Thoughts:
- Maybe make the function check if the text goes off the screen and overflows onto the next line.
- If a new line character is encountered, drop the row by one and continue.

**Comment by zrev2220** [comment]
All of this is completed except for the offscreen check (see the TODO on [line 287](https://github.com/DankZ-CpS230Team/teamProject/blob/89104f45268a20cdafddfc9e239f0b062a0d447e/kernel.asm#L287) of commit 89104f45)
